### ISSUE TITLE
Coverage report miss for external functions

### ISSUE THREAD

**Issue by brettonfinch-wf** [dart-lang/coverage#161] opened 2017-01-23 15:32 UTC
I'm seeing an issue where dart coverage is reporting lines as not being hit when they clearly are being hit. It involves dart bindings to external javascript functions, so I suspect that has something to do with it.

This is an example of what my class I'm testing looks like (bound to external javascript code)

```
@JS()
@anonymous
class TestMe {
  external factory TestMe();
  external int returnFive();
}
```

And my test case. I verified that this test is being run and passing.
```
test('Test ReturnFive returns 5', () {
  var testClass = new TestMe();
  expect(testClass.returnFive(), equals(5));
});
```

When I run coverage for that test though, it reports the line for `returnFive` as not being hit

dart: 1.21.1
coverage: 0.7.3 (also tested with 0.9.1 and issue still occurs)

**Comment by cbracken** [comment] 2017-01-23 17:38
@jacob314 for `package:js`. Not familiar with the implementation of `dart:js` in Dartium, but is it possible we're not generating hits in cases like this?

**Comment by jacob314** [comment] 2017-01-23 17:44
That case would be really hard to support in Dartium. The problem is in that  behind the scenes Dartium is implementing TestMe with noSuchMethod so the "external int returnFive()" isn't really being called. I'd recommend ignoring external methods when tracking your code coverage. DDC should be a much better job at tracking code coverage across the dart-JS boundary.

**Comment by brettonfinch-wf** [comment] 2017-01-23 17:58
@jacob314 What are you referring to with DDC?

**Comment by zoechi** [comment] 2017-01-23 18:00
https://github.com/dart-lang/dev_compiler

**Comment by cbracken** [comment] 2017-01-23 18:06
The current implementation of coverage puts any given line in one of three states:
* Hit
* Miss
* Not coverable

If we can't support marking such lines hit, we should at least ensure that they're not coming back as a miss.

@brettonfinch-wf can you clarify whether the line is coming back with a hit count of 0 (miss) or not included in the generated coverage at all (not coverable)?

**Comment by brettonfinch-wf** [comment] 2017-01-23 18:19
The lines are coming back with a hit count of 0, my project uses CodeCov and it reports those lines as red (missed)

**Comment by cbracken** [comment] 2017-01-23 18:23
Alright - sounds like if it's going to be too painful to get Dartium fixed, in particular with DDC coming, then marking em as un-coverable sounds like the way to go for now. Thanks for confirming!

**Comment by brettonfinch-wf** [comment] 2017-01-23 18:29
Alright, that sounds good to me, thanks for confirming this!

**Comment by cbracken** [comment] 2019-01-15 18:36
Closing as obsolete now that Dartium support is gone. dart-lang/test#36 tracks coverage for Dart for Web scenarios.

**Closed by cbracken** 2019-01-15 18:36 UTC
