### ISSUE TITLE
Dart SDK 1.20.x breaks coverage

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/coverage#134] opened 2016-10-17 15:49 UTC
With the latest SDK release, this package's tests are failing and existing consumptions of this package are broken.

```
$ pub run test
00:08 +17 -1: test/lcov_test.dart: LcovFormatter format()
  Expected: contains '/Users/evanweible/dev/workiva/cp/coverage/lib/src/util.dart'
    Actual: 'SF:/Users/evanweible/dev/workiva/cp/coverage/test/test_files/test_app.dart\n'
    'DA:13,2\n'
    'DA:14,2\n'
    'DA:15,1\n'
    'DA:16,2\n'
    'DA:22,1\n'
    'DA:25,4\n'
    'DA:26,2\n'
    'DA:27,2\n'
    'DA:29,2\n'
    'DA:31,1\n'
    'DA:35,3\n'
    'DA:36,1\n'
    'DA:37,1\n'
    'DA:40,1\n'
    'DA:44,0\n'
    'end_of_record\n'
    'SF:/Users/evanweible/dev/workiva/cp/coverage/test/test_files/test_app_isolate.dart\n'
    'DA:12,1\n'
    'DA:14,1\n'
    'DA:16,3\n'
    'DA:18,1\n'
    'end_of_record\n'
    ''

  package:test                              expect
  test/lcov_test.dart 53:7                  main.<fn>.<fn>.<async>
  dart:async                                _SyncCompleter.complete
  package:coverage/src/formatter.dart 59:5  LcovFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                _Completer.completeError
  test/lcov_test.dart 54:6                  main.<fn>.<fn>.<async>
  dart:async                                _SyncCompleter.complete
  package:coverage/src/formatter.dart 59:5  LcovFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                _asyncThenWrapperHelper
  test/lcov_test.dart                       main.<fn>.<fn>

00:11 +17 -2: test/lcov_test.dart: LcovFormatter format() includes files in reportOn list
  Expected: contains '/Users/evanweible/dev/workiva/cp/coverage/lib/src/util.dart'
    Actual: 'SF:/Users/evanweible/dev/workiva/cp/coverage/test/test_files/test_app.dart\n'
    'DA:13,2\n'
    'DA:14,2\n'
    'DA:15,1\n'
    'DA:16,2\n'
    'DA:22,1\n'
    'DA:25,4\n'
    'DA:26,2\n'
    'DA:27,2\n'
    'DA:29,2\n'
    'DA:31,1\n'
    'DA:35,3\n'
    'DA:36,1\n'
    'DA:37,1\n'
    'DA:40,1\n'
    'DA:44,0\n'
    'end_of_record\n'
    'SF:/Users/evanweible/dev/workiva/cp/coverage/test/test_files/test_app_isolate.dart\n'
    'DA:12,1\n'
    'DA:14,1\n'
    'DA:16,3\n'
    'DA:18,1\n'
    'end_of_record\n'
    ''

  package:test                              expect
  test/lcov_test.dart 66:7                  main.<fn>.<fn>.<async>
  dart:async                                _SyncCompleter.complete
  package:coverage/src/formatter.dart 59:5  LcovFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                _Completer.completeError
  test/lcov_test.dart 67:6                  main.<fn>.<fn>.<async>
  dart:async                                _SyncCompleter.complete
  package:coverage/src/formatter.dart 59:5  LcovFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                _asyncThenWrapperHelper
  test/lcov_test.dart                       main.<fn>.<fn>

00:14 +17 -3: test/lcov_test.dart: LcovFormatter format() excludes files not in reportOn list
  Expected: contains '/Users/evanweible/dev/workiva/cp/coverage/lib/src/util.dart'
    Actual: ''

  package:test                              expect
  test/lcov_test.dart 79:7                  main.<fn>.<fn>.<async>
  dart:async                                _SyncCompleter.complete
  package:coverage/src/formatter.dart 59:5  LcovFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                _Completer.completeError
  test/lcov_test.dart 80:6                  main.<fn>.<fn>.<async>
  dart:async                                _SyncCompleter.complete
  package:coverage/src/formatter.dart 59:5  LcovFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                _asyncThenWrapperHelper
  test/lcov_test.dart                       main.<fn>.<fn>

00:17 +17 -4: test/lcov_test.dart: LcovFormatter format() uses paths relative to basePath
  Expected: contains 'src/util.dart'
    Actual: 'SF:../test/test_files/test_app.dart\n'
    'DA:13,2\n'
    'DA:14,2\n'
    'DA:15,1\n'
    'DA:16,2\n'
    'DA:22,1\n'
    'DA:25,4\n'
    'DA:26,2\n'
    'DA:27,2\n'
    'DA:29,2\n'
    'DA:31,1\n'
    'DA:35,3\n'
    'DA:36,1\n'
    'DA:37,1\n'
    'DA:40,1\n'
    'DA:44,0\n'
    'end_of_record\n'
    'SF:../test/test_files/test_app_isolate.dart\n'
    'DA:12,1\n'
    'DA:14,1\n'
    'DA:16,3\n'
    'DA:18,1\n'
    'end_of_record\n'
    ''

  package:test                              expect
  test/lcov_test.dart 92:7                  main.<fn>.<fn>.<async>
  dart:async                                _SyncCompleter.complete
  package:coverage/src/formatter.dart 59:5  LcovFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                _Completer.completeError
  test/lcov_test.dart 93:6                  main.<fn>.<fn>.<async>
  dart:async                                _SyncCompleter.complete
  package:coverage/src/formatter.dart 59:5  LcovFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                _asyncThenWrapperHelper
  test/lcov_test.dart                       main.<fn>.<fn>

00:20 +17 -5: test/lcov_test.dart: PrettyPrintFormatter format()
  Expected: contains '/Users/evanweible/dev/workiva/cp/coverage/lib/src/util.dart'
    Actual: '/Users/evanweible/dev/workiva/cp/coverage/test/test_files/test_app.dart\n'
    '       |// Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file\n'
    '       |// for details. All rights reserved. Use of this source code is governed by a\n'
    '       |// BSD-style license that can be found in the LICENSE file.\n'
    '       |\n'
    '       |import \'dart:isolate\';\n'
    '       |\n'
    '       |// explicitly using a package import to validate hitmap coverage of packages\n'
    '       |import \'package:coverage/src/util.dart\';\n'
    '       |\n'
    '       |import \'test_app_isolate.dart\';\n'
    '       |\n'
    '       |main() async {\n'
    '      2|  for (var i = 0; i < 10; i++) {\n'
    '      2|    for (var j = 0; j < 10; j++) {\n'
    '      1|      var sum = usedMethod(i, j);\n'
    '      2|      if (sum != (i + j)) {\n'
    '       |        throw \'bad method!\';\n'
    '       |      }\n'
    '       |    }\n'
    '       |  }\n'
    '       |\n'
    '      1|  ReceivePort port = new ReceivePort();\n'
    '       |\n'
    '       |  Isolate isolate =\n'
    '      4|      await Isolate.spawn(isolateTask, [port.sendPort, 1, 2], paused: true);\n'
    '      2|  isolate.addOnExitListener(port.sendPort);\n'
    '      2|  isolate.resume(isolate.pauseCapability);\n'
    '       |\n'
    '      2|  var value = await port.first;\n'
    '       |\n'
    '      1|  if (value != 3) {\n'
    '       |    throw \'expected 3!\';\n'
    '       |  }\n'
    '       |\n'
    '      3|  var result = await retry(() async => 42, const Duration(seconds: 1));\n'
    '      1|  print(result);\n'
    '      1|}\n'
    '       |\n'
    '       |int usedMethod(int a, int b) {\n'
    '      1|  return a + b;\n'
    '       |}\n'
    '       |\n'
    '       |int unusedMethod(int a, int b) {\n'
    '      0|  return a - b;\n'
    '       |}\n'
    '/Users/evanweible/dev/workiva/cp/coverage/test/test_files/test_app_isolate.dart\n'
    '       |// Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file\n'
    '       |// for details. All rights reserved. Use of this source code is governed by a\n'
    '       |// BSD-style license that can be found in the LICENSE file.\n'
    '       |\n'
    '       |import \'dart:io\';\n'
    '       |import \'dart:isolate\';\n'
    '       |\n'
    '       |/// The number of covered lines is tested and expected to be 4.\n'
    '       |///\n'
    '       |/// If you modify this method, you may have to update the tests!\n'
    '       |void isolateTask(List threeThings) {\n'
    '      1|  sleep(const Duration(milliseconds: 500));\n'
    '       |\n'
    '      1|  SendPort port = threeThings.first;\n'
    '       |\n'
    '      3|  var sum = threeThings[1] + threeThings[2];\n'
    '       |\n'
    '      1|  port.send(sum);\n'
    '       |}\n'
    ''

  package:test                               expect
  test/lcov_test.dart 107:7                  main.<fn>.<fn>.<async>
  dart:async                                 _SyncCompleter.complete
  package:coverage/src/formatter.dart 108:5  PrettyPrintFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                 _Completer.completeError
  test/lcov_test.dart 120:6                  main.<fn>.<fn>.<async>
  dart:async                                 _SyncCompleter.complete
  package:coverage/src/formatter.dart 108:5  PrettyPrintFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                 _asyncThenWrapperHelper
  test/lcov_test.dart                        main.<fn>.<fn>

00:23 +17 -6: test/lcov_test.dart: PrettyPrintFormatter format() includes files in reportOn list
  Expected: contains '/Users/evanweible/dev/workiva/cp/coverage/lib/src/util.dart'
    Actual: '/Users/evanweible/dev/workiva/cp/coverage/test/test_files/test_app.dart\n'
    '       |// Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file\n'
    '       |// for details. All rights reserved. Use of this source code is governed by a\n'
    '       |// BSD-style license that can be found in the LICENSE file.\n'
    '       |\n'
    '       |import \'dart:isolate\';\n'
    '       |\n'
    '       |// explicitly using a package import to validate hitmap coverage of packages\n'
    '       |import \'package:coverage/src/util.dart\';\n'
    '       |\n'
    '       |import \'test_app_isolate.dart\';\n'
    '       |\n'
    '       |main() async {\n'
    '      2|  for (var i = 0; i < 10; i++) {\n'
    '      2|    for (var j = 0; j < 10; j++) {\n'
    '      1|      var sum = usedMethod(i, j);\n'
    '      2|      if (sum != (i + j)) {\n'
    '       |        throw \'bad method!\';\n'
    '       |      }\n'
    '       |    }\n'
    '       |  }\n'
    '       |\n'
    '      1|  ReceivePort port = new ReceivePort();\n'
    '       |\n'
    '       |  Isolate isolate =\n'
    '      4|      await Isolate.spawn(isolateTask, [port.sendPort, 1, 2], paused: true);\n'
    '      2|  isolate.addOnExitListener(port.sendPort);\n'
    '      2|  isolate.resume(isolate.pauseCapability);\n'
    '       |\n'
    '      2|  var value = await port.first;\n'
    '       |\n'
    '      1|  if (value != 3) {\n'
    '       |    throw \'expected 3!\';\n'
    '       |  }\n'
    '       |\n'
    '      3|  var result = await retry(() async => 42, const Duration(seconds: 1));\n'
    '      1|  print(result);\n'
    '      1|}\n'
    '       |\n'
    '       |int usedMethod(int a, int b) {\n'
    '      1|  return a + b;\n'
    '       |}\n'
    '       |\n'
    '       |int unusedMethod(int a, int b) {\n'
    '      0|  return a - b;\n'
    '       |}\n'
    '/Users/evanweible/dev/workiva/cp/coverage/test/test_files/test_app_isolate.dart\n'
    '       |// Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file\n'
    '       |// for details. All rights reserved. Use of this source code is governed by a\n'
    '       |// BSD-style license that can be found in the LICENSE file.\n'
    '       |\n'
    '       |import \'dart:io\';\n'
    '       |import \'dart:isolate\';\n'
    '       |\n'
    '       |/// The number of covered lines is tested and expected to be 4.\n'
    '       |///\n'
    '       |/// If you modify this method, you may have to update the tests!\n'
    '       |void isolateTask(List threeThings) {\n'
    '      1|  sleep(const Duration(milliseconds: 500));\n'
    '       |\n'
    '      1|  SendPort port = threeThings.first;\n'
    '       |\n'
    '      3|  var sum = threeThings[1] + threeThings[2];\n'
    '       |\n'
    '      1|  port.send(sum);\n'
    '       |}\n'
    ''

  package:test                               expect
  test/lcov_test.dart 133:7                  main.<fn>.<fn>.<async>
  dart:async                                 _SyncCompleter.complete
  package:coverage/src/formatter.dart 108:5  PrettyPrintFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                 _Completer.completeError
  test/lcov_test.dart 134:6                  main.<fn>.<fn>.<async>
  dart:async                                 _SyncCompleter.complete
  package:coverage/src/formatter.dart 108:5  PrettyPrintFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                 _asyncThenWrapperHelper
  test/lcov_test.dart                        main.<fn>.<fn>

00:26 +17 -7: test/lcov_test.dart: PrettyPrintFormatter format() excludes files not in reportOn list
  Expected: contains '/Users/evanweible/dev/workiva/cp/coverage/lib/src/util.dart'
    Actual: ''

  package:test                               expect
  test/lcov_test.dart 147:7                  main.<fn>.<fn>.<async>
  dart:async                                 _SyncCompleter.complete
  package:coverage/src/formatter.dart 108:5  PrettyPrintFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                 _Completer.completeError
  test/lcov_test.dart 148:6                  main.<fn>.<fn>.<async>
  dart:async                                 _SyncCompleter.complete
  package:coverage/src/formatter.dart 108:5  PrettyPrintFormatter.format.<async>
  ===== asynchronous gap ===========================
  dart:async                                 _asyncThenWrapperHelper
  test/lcov_test.dart                        main.<fn>.<fn>

00:26 +17 -7: Some tests failed.
```

**Comment by evanweible-wf** [comment] 2016-10-17 15:49
@cbracken @kevmoo

**Comment by cbracken** [comment] 2016-10-17 16:38
Thanks for reporting! Will take a look.

**Comment by cbracken** [comment] 2016-10-17 17:23
The test failures were caused by our tests configuring their resolver to use the `packages` dir instead of the `.packages` file to resolve packages. I added support for package-spec based resolution in 402b821104e58c0b5e5c583af2e64fb9d21a194c, and updated the README to prefer that method, but apparently failed to update the tests to prefer using `.packages` files at the time. 

Can you take a quick look at how you're calling `format_coverage` and verify that you're passing the `--packages` option rather than `--package-root`? If so, and you're still running into issues, let me know.

**Comment by evanweible-wf** [comment] 2016-10-17 17:44
@cbracken looking into that now, thanks!

**Comment by cbracken** [comment] 2016-10-17 18:17
np! Merged #135, which fixes the tests. Thanks again for reporting. I'll close for now, but please re-open if you find the `--packages` flag doesn't work for you.

**Closed by cbracken** 2016-10-17 18:17 UTC

**Comment by evanweible-wf** [comment] 2016-10-25 06:43
Forgot to report back, but the --package-root option did fix the issue I was seeing. Thanks again @cbracken

**Comment by cbracken** [comment] 2016-10-25 16:21
Thanks for letting me know!
