### ISSUE TITLE
Coverage doesn't include branch and function information?

### ISSUE THREAD

**Issue by Hixie** [dart-lang/coverage#344] opened 2021-05-04 05:33 UTC
When I run `flutter test --coverage` and then `lcov --summary coverage/lcov.info`, it says `functions: no data found` and `branches: no data found`. I'm no expert but that would seem to suggest that the `lcov.info` format now supports more than we are currently exposing.

**Comment by IchordeDionysos** [comment] 2021-06-14 17:02
Yes, coverage information in an LCOV file can include the number of 
- functions covered with tests vs the number of total functions found and
- the number of branches (if/else, switch/case, ...) covered and found.

Especially, the last one can be very helpful when you want to ensure that every single part of the application is tested and to make sure that someone does not miss the else part of an if statement during the tests!

Here is a bit of documentation on the file format which explains how this works in the LCOV file format:
http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php

I would very much appreciate having branch coverage! 💪 
(Function coverage is not so important for us)

**Comment by liamappelbe** [comment] 2021-12-14 01:14
Dupe of https://github.com/dart-lang/coverage/issues/141

**Closed by liamappelbe** 2021-12-14 01:14 UTC
