### ISSUE TITLE
Coverage failing w/ 2.0.0-dev.5 sdk

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/coverage#200] opened 2017-11-02 16:22 UTC
https://travis-ci.org/dart-lang/coverage/jobs/295851657

**Comment by cbracken** [comment] 2017-11-02 17:03
I might be missing something, but this looks more like a pub timeout than something coverage-related.

**Comment by cbracken** [comment] 2017-11-02 17:07
On re-running I get a failure. The good news is it's an intentional check I put in specifically to catch when the SDK containing the bugfix for #196 rolled out. Closing as dupe of #196.

**Closed by cbracken** 2017-11-02 17:07 UTC

**Comment by cbracken** [comment] 2017-11-02 17:57
FYI tests updated in #201 for Dart SDK 2.0.0-dev.5.0 and #202 for Dart SDK 2.0.0-dev.6.0.
