### ISSUE TITLE
Test coverage doesn't work when using pattern matching to destructure a record

### ISSUE THREAD

**Issue by Kirpal** [dart-lang/coverage#479] opened 2024-01-31 23:06 UTC
# Description
When I define variables by destructuring a record, the line with the variable definition is saying it's not covered, even though it's being executed.

# Example

```dart
// main.dart
int getSum() {
  final (a, b, c) = (1, 2, 3); // This line is not getting covered.

  return a + b + c;
}

// main_test.dart
void main() {
  test('getSum works', () {
    expect(getSum(), 6);
  });
}
```

**Comment by liamappelbe** [comment] 2024-02-01 00:16
Duplicate of https://github.com/dart-lang/sdk/issues/53519

We're working on it. Should be fixed pretty soon.

**Closed by liamappelbe** 2024-02-01 00:16 UTC
